### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by ronyrun** [eHealthAfrica/pouchdb-migrate#12]
Hello, Thank you for your work !

Is it possible to add it to Bower ?

**Comment by jo** [comment]
Sure!

That would mean adding a _bower.json_, like eg. [this one](https://github.com/eHealthAfrica/angular-eha.couchdb-auth/blob/master/bower.json), right? What other steps are needed?

Could you make that PR?

**Comment by ronyrun** [comment]
Hello @jo,
I'm not very familiar with bower.  
But related to http://bower.io/docs/creating-packages/ indeed we need to define a bower.json.
Also I don't know what are the dependencies to your source...

But yes it's like the one you posted.

**Comment by danse** [comment]
Bower has an `init` command that will guide you through the process, just type `bower init`

**Comment by danse** [comment]
i think that there is a registry of Bower packages, anyway Bower supports Github endpoints as far as i know, so once the Bower file will be in place it will be sufficient to run:

    bower install eHealthAfrica/pouchdb-migrate#tag

in order to install a tag. actually this already works even without having a Bower file here, just try:

    bower install eHealthAfrica/pouchdb-migrate#v1.1.1

**Comment by jo** [comment]
Thanks @danse. I created the bower.json via `bower init` and changed main to point to the browserify build. Does #13 look good?

**Comment by jo** [comment]
Thank you @ronyrun and @danse :rose:

**Comment by danse** [comment]
:sunflower:

**Comment by ronyrun** [comment]
Thank you @danse and @jo !! :D
