### ISSUE TITLE
The Boing Bug

### ISSUE THREAD

**Issue by garrensmith** [eHealthAfrica/pouchdb-migrate#22]
This migration is exactly what I want. Thanks for writing this. I've run into a weird issue.
If I create a migration. Then I run it, it works fine. Then if I immediately run that migration again then pouchdb-migrate just seems to loop and from what I can see it continuously saves the docs. I have a doc with 707-... revision number.

I'm using Couchdb 2.0 built from master. But n = 1 and admin party mode.

**Comment by jo** [comment]
Hi @garrensmith, thanks for reporting, I will refer to that issue as the Bond Bug :)

Could you provide more information about how and with which options you run the migration?

**Comment by jo** [comment]
Hi @garrensmith, thanks for reporting, I will refer to that issue as the Bond Bug :)

Could you provide more information about how and with which options you run the migration?

**Comment by jo** [comment]
Hi @garrensmith, thanks for reporting! I will refer to that issue as the Boing Bug :)

Could you provide more information about how and with which options you run the migration?

**Comment by garrensmith** [comment]
Hi @jo, I've renamed the issue to __The Boing Bug__ :)
Below is my migration code:

```javascript
var migrationBooking = function(doc) {
  if (doc.type !== 'booking') {
    return false;
  }

  doc.type = 'booking/v1';
  return [doc];
};

var migrationUser = function (doc) {
  if (doc.scope !== 'user') {
    return false;
  }

  if (doc.type) {
    return false;
  }

  doc.type = 'user/v1';

  var businessDoc = {
    _id: uuid.v4(),
    countryCode: doc.country,
    company: doc.company,
    type: 'business/v1'
  };

  doc.businessId = businessDoc._id;
  return [doc, businessDoc];
};

db.migrate(migrationBooking)
  .then(function () {
    return db.migrate(migrationUser);
  })
  .then(function (res) {
    console.log('Migrate complete!', res);
  })
  .catch(function (err) {
    console.log('ERR ', err);
  });
```

**Comment by jo** [comment]
Hi @garrensmith,

I [stubbed a test](https://github.com/eHealthAfrica/pouchdb-migrate/pull/23) to reproduce the problem, but it worked :(
Could you please complete and make that test fail?

**Comment by garrensmith** [comment]
Awesome. I'll take a look. Thanks for the great help. 

All misspelling thanks to my iPhone

**Comment by garrensmith** [comment]
Ok I cannot reproduce either. I've tried a couple ways. I'm really sorry for wasting your time on this. 
I'll close this issue.

**Comment by jo** [comment]
No worries :)

**Comment by tlvince** [comment]
@garrensmith, @jo (hey 👋), I can reproduce this when the migration returns the doc unchanged. How does #28 look your end?
